/**
 * Extract JSDoc/TSDoc from source files and write markdown to docs/generated/from-code/.
 * Used by pnpm docs:generate to build "docs from code comments".
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '../..');
const srcDir = path.join(root, 'src');
const outDir = path.join(root, 'docs', 'generated', 'from-code');

/** Source files to extract comments from (paths relative to src/) */
const SOURCE_FILES = [
  'core/schema-engine/index.ts',
  'lib/nextpress.ts',
  'nextpress.config.ts',
  'scripts/generate-schema.ts',
  'scripts/run-migration.ts',
  'scripts/generate-docs.ts',
  'core/collection/types.ts',
];

const JSDOC_BLOCK = /\/\*\*([\s\S]*?)\*\//g;

function jsdocToMarkdown(block: string): string {
  const lines = block
    .trim()
    .split('\n')
    .map((line) => line.replace(/^\s*\*\s?/, '').trim())
    .filter(Boolean);
  const out: string[] = [];
  let inTag = false;
  for (const line of lines) {
    if (line.startsWith('@')) {
      if (!inTag) out.push('');
      inTag = true;
      out.push(`- **${line.slice(0, line.indexOf(' ') + 1).trim()}** ${line.slice(line.indexOf(' ') + 1).trim()}`);
    } else {
      inTag = false;
      out.push(line);
    }
  }
  return out.join('\n').trim();
}

function extractFileLevelJsdoc(content: string): string | null {
  const trimmed = content.trimStart();
  if (!trimmed.startsWith('/**')) return null;
  const match = trimmed.match(/^\/\*\*([\s\S]*?)\*\//);
  if (!match) return null;
  return jsdocToMarkdown(match[1]);
}

function extractExportJsdocs(content: string): { name: string; doc: string }[] {
  const results: { name: string; doc: string }[] = [];
  const lines = content.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!/^\s*export\s+(async\s+)?(function|const|class|interface|type|enum)\s+(\w+)/.test(line)) continue;
    const nameMatch = line.match(/(?:function|const|class|interface|type|enum)\s+(\w+)/);
    const name = nameMatch ? nameMatch[1] : 'unknown';
    const textBeforeExport = lines.slice(0, i).join('\n');
    const blocks: string[] = [];
    let m: RegExpExecArray | null;
    const re = /\/\*\*([\s\S]*?)\*\//g;
    while ((m = re.exec(textBeforeExport)) !== null) blocks.push(m[1]);
    const lastBlock = blocks[blocks.length - 1];
    if (!lastBlock) continue;
    results.push({ name, doc: jsdocToMarkdown(lastBlock) });
  }
  return results;
}

function moduleNameFromPath(relativePath: string): string {
  const base = path.basename(relativePath, path.extname(relativePath));
  const dir = path.dirname(relativePath);
  if (!dir || dir === '.' || dir === 'src') return base;
  const segments = dir.split(path.sep).filter(Boolean);
  const last = segments[segments.length - 1];
  if (last === base || base === 'index') return last;
  return `${last}-${base}`;
}

function processFile(relativePath: string): { module: string; md: string } | null {
  const fullPath = path.join(srcDir, relativePath);
  if (!fs.existsSync(fullPath)) return null;
  const content = fs.readFileSync(fullPath, 'utf-8');
  const fileDoc = extractFileLevelJsdoc(content);
  const exportDocs = extractExportJsdocs(content);
  const module = moduleNameFromPath(relativePath);
  const parts: string[] = [
    `# ${module}`,
    '',
    `*Generated from \`src/${relativePath}\`. Run \`pnpm docs:generate\` to update.*`,
    '',
  ];
  if (fileDoc) {
    parts.push(fileDoc);
    parts.push('');
  }
  if (exportDocs.length > 0) {
    parts.push('## Exports');
    parts.push('');
    for (const { name, doc } of exportDocs) {
      parts.push(`### ${name}`);
      parts.push('');
      parts.push(doc);
      parts.push('');
    }
  }
  return { module, md: parts.join('\n').trim() };
}

export function runExtractJsdoc(): void {
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  const index: string[] = ['# Docs from code comments', '', 'Generated by `pnpm docs:generate`.', ''];
  for (const rel of SOURCE_FILES) {
    const result = processFile(rel);
    if (!result) continue;
    const outPath = path.join(outDir, `${result.module}.md`);
    fs.writeFileSync(outPath, result.md);
    index.push(`- [${result.module}](./from-code/${result.module}.md)`);
  }
  fs.writeFileSync(path.join(outDir, 'README.md'), index.join('\n'));
}
